### ISSUE TITLE
Error with org.sonar.api.resources.Project.getAnalysisDate

### ISSUE THREAD

**Issue by cybrus** [dbac2002/sonar-hipchat-plugin#9]
I'm getting this error when trying to run version 0.2 with SonarQube Version 6.3.1 (build 21392)

```
Caused by: java.lang.NoSuchMethodError: org.sonar.api.resources.Project.getAnalysisDate()Ljava/util/Date;
at com.sonar.hipchat.plugin.SonarHipChatMessageBuilder.getStatusMessage(SonarHipChatMessageBuilder.java:59)
at com.sonar.hipchat.plugin.HipChatHttpClient.sendStatusNotification(HipChatHttpClient.java:90)
at com.sonar.hipchat.plugin.SonarHipChatNotifier.executeOn(SonarHipChatNotifier.java:44)
```

**Comment by seenusankara** [comment]
facing the same issue
![sonar-hipchat](https://user-images.githubusercontent.com/8611962/44016697-734981f4-9ef3-11e8-98b8-7f5c60724671.PNG)
